### ISSUE TITLE
Allow this app to be used as home screen

### ISSUE THREAD

**Issue by legovini** [SimpleMobileTools/Simple-App-Launcher#3]
I think there the need for a "Simple launcher" (home screen). It would be nice to use this app as launcher, possibly supporting widgets, or to have another dedicated app that just shows widgets and launches this App Launcher as its "drawer".

**Comment by tibbi** [comment]
hah ye, maybe one day I will get there as that's the next logical step. There is just so much more work to make it a real Launcher, I will focus on improving the remaining apps first

**Comment by tibbi** [comment]
Ill close it as its not an issue, a real Launcher might come in the future. Stay tuned ;)

**Comment by NicoHood** [comment]
Hi,
its been two years now, since the original opening of the issue. I recently started using your apps, and I love them! I want to replace every builtin/google app with your software, because I do not want to send all my data to google.

One of the reasons why an app launcher as home screen would make sense it to get rid of the "ok google" widget. It seems you cannot remove it (on android one) without completely loosing google play store support. It just takes space, so removing it with another launcher would be nice.

**Comment by tibbi** [comment]
I still want to work on improving the existing apps first, then there are a few other new apps on the roadmap already. So dont really expect a Simple Launcher anytime soon.

**Comment by 3j9fkyahunqoxwqu** [comment]
Also please keep this version if you wanted to make it a real launcher.
This is great
Thanks

**Comment by ioogithub** [comment]
I would also request to make this app a real launcher. I have tried many launchers and this is  the one I want.

**Comment by mariobrostech** [comment]
I wanted to chime in and give my opinion too. I don't care if some people consider this app "too barebones" to be a launcher, and I think you should give your users a choice. We don't _have_ to make this their default launcher, but we should at least have the option to if we desire. And, as the app continues to improve via updates, we get to enjoy those new features as well, and more users will begin to consider using this app as their default launcher. Just my two cents.

**Comment by hacknorris-aka-penguin** [comment]
me too....
