### ISSUE TITLE
Use a translation service to translate all your apps

### ISSUE THREAD

**Issue by vanitasvitae** [SimpleMobileTools/Simple-App-Launcher#5]
Hi!
Why don't you put your apps up on some translation service, so that people can translate your apps to make them available for more people?

I know its possible to translate apps via pull requests, but I think a translation service like eg. crowdin.com is also accessbile for non-developers.

On crowdin you can apply for a free opensource license.

**Comment by tibbi** [comment]
Hey, 
well I see the statistics of users, and english is by faaar the most used system language. Then a couple percent here and there, no language is worth heavily translating. 
I honestly didnt want any translations yet because the apps are still just under early development and having to take care of the other string files or editing strings slow me down. People created pull requests with some translations tho which surprised me positively, so I obviously didnt want to refuse :)
