### ISSUE TITLE
Support for old android versions? i.e. 4.* . Can it support those after few changes?

### ISSUE THREAD

**Issue by QaisarRajput** [SimpleMobileTools/Simple-App-Launcher#74]
I want to recompile the code. but the version i have on the device is 4.*, While the following [link ](https://f-droid.org/packages/com.simplemobiletools.applauncher/) shows that it supports android 5.0 or higher.
Can you please suggest how to make work on older versions and what changes may be required in order to do it.

**Comment by tibbi** [comment]
many changes would be needed, I dont plan supporting them anymore

**Comment by QaisarRajput** [comment]
I understand. but is there an old stable release? i see this [commit ](https://github.com/SimpleMobileTools/Simple-App-Launcher/commit/6b39423cf1417ce83c1a1c0aa9a302041225e2bd). If i get this commit, will i be able to compile and run an older version of the application? or something else has changed which may cause some issues.

**Comment by tibbi** [comment]
the required OS version has been increased in version 5.0 of all apps. So version 4.x whichever should work just fine

**Comment by QaisarRajput** [comment]
sounds great. thanks

**Comment by unforgettableid** [comment]
Dear @QaisarRajput:

Maybe you can unlock your phone's bootloader.  If so, you might be able to install a custom ROM such as LineageOS, which will give you a newer Android version than you could get otherwise.

Some phones do not have an unlockable bootloader.  If you cannot unlock your phone's bootloader:  You can go to a store which sells used phones.  You can buy an old, cheap phone with an unlockable bootloader, and then maybe you can upgrade it to the newest version of LineageOS.

[This page](https://wiki.lineageos.org/devices) lists dozens of old devices which still support LineageOS.  Some very old devices are supported:  including, for example, many Samsung Galaxy S4, S5, and S9 variants.

Installing a custom ROM will void your phone's warranty.
